os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
install:
- sudo apt-get install sshpass
script:
- docker build -t otakushelter/frontends:1.0.${TRAVIS_BUILD_NUMBER} -f src/OtakuShelter.Frontend/Dockerfile .
- docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
- docker push otakushelter/frontends:1.0.$TRAVIS_BUILD_NUMBER
- |
  sudo sshpass -p $ANSIBLE_PASSWORD ssh -o StrictHostKeyChecking=no $ANSIBLE_CONNECTION \
    "cd /root/OtakuShelter.Infrastructure/src && \
    ansible-playbook deploy.yml \
    -e \"\
    otakushelter_hosts=frontends \
    otakushelter_port=4004 \
    otakushelter_image=otakushelter/frontends \
    otakushelter_server_name=staging.otaku-shelter.ru \
    otakushelter_build_number=$TRAVIS_BUILD_NUMBER \" \
    -i inventories/staging"