os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: 
- docker
- sshpass

script:
- docker-compose build
- docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
- docker push otakushelter/frontend:1.0.$TRAVIS_BUILD_NUMBER
- sudo chmod +x ./deploy.sh
- ./deploy.sh | sudo sshpass -p $FRONTEND_PASSWORD ssh -o StrictHostKeyChecking=no $FRONTEND_CONNECTION